### ISSUE TITLE
OpenAction Collect with multirecipient contract returns error in lensclient V2 alpha 11

### ISSUE THREAD

**Issue by mvanhalen** [lens-protocol/lens-sdk#608]
**Describe the bug**
When collecting this post 0x28-0x06 with multirecipientCollectOpenActionSettings from lens v2 developer preview the following error returns:

`{
    "errors": [
        {
            "message": "Variable \"$request\" got invalid value { multirecipientCollectOpenAction: true } at \"request.actOn\"; Field \"multirecipientCollectOpenAction\" is not defined by type \"ActOnOpenActionLensManagerInput\". Did you mean \"simpleCollectOpenAction\"?",
            "locations": [
                {
                    "line": 1,
                    "column": 26
                }
            ],
            "extensions": {
                "code": "BAD_USER_INPUT",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Variable \"$request\" got invalid value { multirecipientCollectOpenAction: true } at \"request.actOn\"; Field \"multirecipientCollectOpenAction\" is not defined by type \"ActOnOpenActionLensManagerInput\". Did you mean \"simpleCollectOpenAction\"?",
                        "    at /usr/src/app/node_modules/graphql/execution/values.js:116:15",
                        "    at coerceInputValueImpl (/usr/src/app/node_modules/graphql/utilities/coerceInputValue.js:114:9)",
                        "    at coerceInputValueImpl (/usr/src/app/node_modules/graphql/utilities/coerceInputValue.js:54:14)",
                        "    at coerceInputValueImpl (/usr/src/app/node_modules/graphql/utilities/coerceInputValue.js:105:34)",
                        "    at coerceInputValueImpl (/usr/src/app/node_modules/graphql/utilities/coerceInputValue.js:54:14)",
                        "    at coerceInputValue (/usr/src/app/node_modules/graphql/utilities/coerceInputValue.js:37:10)",
                        "    at _loop (/usr/src/app/node_modules/graphql/execution/values.js:109:69)",
                        "    at coerceVariableValues (/usr/src/app/node_modules/graphql/execution/values.js:121:16)",
                        "    at getVariableValues (/usr/src/app/node_modules/graphql/execution/values.js:50:19)",
                        "    at buildExecutionContext (/usr/src/app/node_modules/graphql/execution/execute.js:203:61)",
                        "    at executeImpl (/usr/src/app/node_modules/graphql/execution/execute.js:101:20)",
                        "    at Object.execute (/usr/src/app/node_modules/graphql/execution/execute.js:60:35)",
                        "    at /usr/src/app/node_modules/apollo-server-core/dist/requestPipeline.js:261:48",
                        "    at Generator.next (<anonymous>)",
                        "    at /usr/src/app/node_modules/apollo-server-core/dist/requestPipeline.js:8:71",
                        "    at new Promise (<anonymous>)"
                    ]
                }
            }
        }
    ]
}`

Using the following query
`{
    "for": "0x28-0x06",
    "actOn": {
        "multirecipientCollectOpenAction": true
    }
}`

Using profile 0x28 test/@collectz and 0xdd test/@collector both with profile manager enabled (lensManager = true)

 **To Reproduce**
Happens each time. Allowance has been set. 

**Expected behavior**
That works. No errors expected.

**Version of the packages you are using**
lensclient V2 alpha 11

**Comment by cesarenaldi** [comment]
The error is correct in the sense that it's not possible to perform paid collect via Lens Manager.

<img width="1193" alt="image" src="https://github.com/lens-protocol/lens-sdk/assets/3353250/daca4769-969c-4712-a775-6bcfb05bdb8e">
