### ISSUE TITLE
Support wagmi v2

### ISSUE THREAD

**Issue by daoleno** [lens-protocol/lens-sdk#800]
**Is your feature request related to a problem? Please describe.**
After upgrading to wagmi v2, I encountered the following error while using the `useLogin` hook.

```
TypeError: Cannot read properties of undefined (reading 'connections')
    at getConnectorClient (getConnectorClient.ts:75:30)
    at getWalletClient (getWalletClient.ts:43:17)
    at _callee2$ (lens-protocol-wagmi.esm.js:406:26)
    at tryCatch (lens-protocol-wagmi.esm.js:48:7)
    at Generator.<anonymous> (lens-protocol-wagmi.esm.js:136:13)
    at Generator.next (lens-protocol-wagmi.esm.js:77:7)
    at asyncGeneratorStep (lens-protocol-wagmi.esm.js:310:22)
    at _next (lens-protocol-wagmi.esm.js:329:7)
    at lens-protocol-wagmi.esm.js:334:5
    at new Promise (<anonymous>)
  ```

**Describe the solution you'd like**
Integrate Lens SDK seamlessly with wagmi v2.

**Comment by cesarenaldi** [comment]
hey @daoleno , thank you for reporting. Will let you know when wagmi v2 will be officially supported.

**Comment by cesarenaldi** [comment]
An update on this: https://github.com/lens-protocol/lens-sdk/pull/835

**Comment by cesarenaldi** [comment]
@daoleno support for Wagmi v2 is available from `@lens-protocol/wagmi@4.0.0-alpha.0`.

**Comment by cesarenaldi** [comment]
Updated reference docs: https://lens-protocol.github.io/lens-sdk/modules/_lens_protocol_react_web.Core.html

**Comment by cesarenaldi** [comment]
The version mentioned above is now update. See https://github.com/lens-protocol/lens-sdk/issues/852
